name: Nightly Scan
on:
  workflow_dispatch:
    inputs:
  schedule:
    - cron: "0 5 * * *" # UTC

env:
  REGISTRY: ghcr.io

jobs:
  publish-scan-branch:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        branch:
          - main

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ matrix.branch }}

      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Log into registry ${{env.REGISTRY}}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Publish image
        id: publish-kyverno-notation-aws
        run: |
          make docker-publish IMAGE_NAME=nightly-kyverno-notation-aws

      - name: image scanning
        id: scan
        uses: nirmata/reusable-workflows/.github/actions/image-scanning@cleanup
        with:
          pcc_url: ${{ secrets.PCC_URL }}
          pcc_user: ${{ secrets.PCC_USER }}
          pcc_pass: ${{ secrets.PCC_PASS }}
          image_name: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
          free-disk: 'true'

  publish-scan-tags:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        tag:
          - v4.1.1

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ matrix.tag }}

      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Set Image name
        run: |
          echo IMAGE_NAME="nirmata/nightly-nctl" >> $GITHUB_ENV
      
      - name: Install KO
        uses: ko-build/setup-ko@3aebd0597dc1e9d1a26bcfdb7cbeb19c131d3037 # v0.7

      - name: Log into registry ${{env.REGISTRY}}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}


      - name: Build and Push 
        run: |
          make build-ko KO_REGISTRY=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} KO_TAGS=${{ matrix.tag }}

      - name: image scanning
        id: scan
        uses: nirmata/reusable-workflows/.github/actions/image-scanning@main
        with:
          pcc_url: ${{ secrets.PCC_URL }}
          pcc_user: ${{ secrets.PCC_USER }}
          pcc_pass: ${{ secrets.PCC_PASS }}
          image_name: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{ matrix.tag }}