name: Unit Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Setup build env
        uses: ./.github/actions/setup-build-env
        with:
          build-cache-key: tests
      - name: Unit test
        run: make test-unit
